/**
 * Humanização de texto — segunda passagem dedicada a quebrar padrões estatísticos de IA.
 *
 * Detectores como GPTZero/Originality.ai medem:
 *   • Perplexidade      — imprevisibilidade de cada token dado o contexto
 *   • Burstiness        — variância no comprimento de frases
 *   • Voz pessoal       — presença de primeira pessoa e opiniões do autor
 *   • Expressões clichê — frases-padrão de IA que detectores reconhecem
 *
 * Instruções no prompt de geração não resolvem: o modelo produz tokens na sua
 * distribuição padrão. A única solução confiável é uma segunda chamada que
 * aplica transformações cirúrgicas sobre o rascunho já gerado.
 */

export const HUMANIZADOR_SYSTEM = `Você é um especialista sênior em reescrita de textos acadêmicos em português brasileiro. Sua única tarefa é receber um rascunho de texto científico e reescrevê-lo para soar genuinamente humano, driblando os detectores de IA.

Você conhece profundamente como o GPTZero, Originality.ai e Turnitin funcionam. Sabe que eles detectam: ausência de voz pessoal, expressões clichê de IA, frases de comprimento uniforme, conectivos previsíveis, e falta de incerteza genuína.`

export function buildHumanizadorPrompt(rascunho: string): string {
  return `Reescreva o texto acadêmico abaixo para que passe em detectores de IA com score abaixo de 25%. Mantenha 100% do conteúdo técnico, dados e estrutura de seções.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 0 — REMOÇÃO IMEDIATA DE METADADOS DE IA (PRIORIDADE MÁXIMA)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ELIMINE completamente qualquer linha ou trecho que contenha:
- "Gerado em" / "Generated on" / "Generated by"
- "Científica AI" / "Científica.ai" / nome de qualquer aplicativo de IA
- "AI-assisted" / "Assistido por IA" / "Produzido com auxílio de IA"
- "Data de geração:" ou qualquer cabeçalho de metadado
Esses marcadores são bandeiras vermelhas imediatas para qualquer detector.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 1 — VOZ PESSOAL (o problema mais detectado)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Detectores identificam "Absence of personal voice" como sinal primário de IA.
Insira voz acadêmica pessoal (primeira pessoa plural) em pelo menos 6 frases:
✓ "neste estudo, optamos por..." (em vez de "o estudo utilizará...")
✓ "nossa análise seguirá..." (em vez de "a análise seguirá...")
✓ "identificamos como limitação..."
✓ "partimos do pressuposto de que..."
✓ "entendemos que essa abordagem..."
✓ "ao examinar os dados, percebemos que..."
✓ "nossa escolha pelo [software] se justifica porque..."
Use "nós/nosso/nossa" de forma natural — é prática comum em artigos científicos brasileiros.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 2 — CLICHÊS CIENTÍFICOS DE IA (eliminar todos)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Substitua CADA ocorrência das expressões abaixo por alternativa menos previsível:
❌ "padrão-ouro" → "referência metodológica consolidada" ou "método de referência"
❌ "amplamente utilizado" → "frequentemente adotado" ou "já consagrado na área"
❌ "literatura científica" → "produção científica disponível" ou "evidências publicadas"
❌ "é importante ressaltar" → comece direto com o conteúdo
❌ "cabe destacar" → comece direto com o conteúdo
❌ "diante do exposto" → remova ou use "por essa razão"
❌ "nesse contexto" → remova ou use "nessa situação específica"
❌ "além disso," no início → remova ou reescreva sem o conectivo
❌ "sendo assim" → "por isso" ou remova
❌ "outrossim" → remova completamente
❌ "destarte" → remova completamente
❌ "no que tange" → "sobre" ou "quanto a"
❌ "em suma" → "em síntese" ou nada
❌ "robusto/robusta" (quando aplicado a métodos/análises) → "consistente" ou "sólido"
❌ "abrangente" → "amplo" ou "extenso"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 3 — BURSTINESS (variância de comprimento de frases)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Toda sequência de 3+ frases com comprimento parecido (12-25 palavras) é sinal de IA.
Para cada sequência encontrada: encurte 1 delas para menos de 7 palavras.
Meta: distribuição como 4, 27, 6, 19, 42, 5, 23 palavras — não 16, 18, 17, 15.
Também: expanda ocasionalmente 1 frase para 45+ palavras (frase-parágrafo técnica).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 4 — ESPECIFICIDADE E INCERTEZA GENUÍNA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Detectores identificam "Lack of specificity" como sinal de IA genérica.
Adicione em pelo menos 4 lugares distintos:
- Um dado numérico concreto plausível para este estudo
- Uma expressão de incerteza: "na maioria dos cenários", "em geral", "(isso pode variar)"
- Uma limitação real do método: "embora esse teste assuma...", "isso só funciona quando..."
- Um parentético prático: "(o que na prática significa cerca de X dias)", "(exceto com N < 30)"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 5 — VARIAÇÃO LEXICAL
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Em cada parágrafo, substitua pelo menos 1 verbo/substantivo previsível:
"realizar" → "conduzir" / "executar" / "levar a cabo"
"apresentar" → "revelar" / "mostrar" / "exibir"
"verificar" → "constatar" / "checar" / "atestar"
"analisar" → "examinar" / "investigar" / "debruçar-se sobre"
"observar" → "notar" / "perceber" / "identificar"
"utilizar" → "usar" / "empregar" / "adotar" / "lançar mão de"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMAÇÃO 6 — CONVERSÃO PARCIAL DE LISTAS + PERGUNTA RETÓRICA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Converta 2-3 itens de lista em prosa incorporada ao parágrafo anterior
• Insira 1 pergunta retórica em alguma seção introdutória ou de conclusão
• Adicione 1 contradição ou ressalva inesperada: "curiosamente, X não implica Y"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRESERVAR ABSOLUTAMENTE — não altere nada disso
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✓ Dados numéricos, fórmulas e cálculos
✓ Blocos de código de software (entre \`\`\` — não toque)
✓ Referências ABNT e citações bibliográficas
✓ Campos entre [COLCHETES] — são placeholders para o pesquisador preencher
✓ Títulos numerados das seções (1., 2., 3. etc.)
✓ Termos técnicos e jargão da área
✓ Formatação markdown: **, ##, listas que NÃO foram convertidas

ENTREGUE APENAS o texto reescrito. Zero comentários, zero explicações, zero cabeçalhos novos.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RASCUNHO PARA REESCREVER:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${rascunho}`
}
