import type { ConfiguracaoFluxo } from '@/types'

export const FLUXOS: Record<string, ConfiguracaoFluxo> = {
  tcc: {
    tipo: 'tcc',
    nome_completo: 'TCC — Trabalho de Conclusão de Curso',
    descricao: 'Requisito final da graduação. Do tema à defesa.',
    nivel: ['graduacao'],
    duracao_estimada_horas: 20,
    requer_cep: false,
    requer_prisma: false,
    formatos_citacao_recomendados: ['abnt'],
    fases: [
      {
        id: 'tema',
        chave_secao: 'tema',
        nome: 'Tema e Delimitação',
        descricao: 'Escolha e delimite o tema do seu TCC',
        obrigatoria: true,
        tempo_estimado_minutos: 15,
        instrucoes: 'Defina o tema geral e a delimitação específica. O tema deve ser relevante para sua área e viável dentro do prazo.',
        dicas_ia: [
          'Seja específico: não "diabetes", mas "controle glicêmico em idosos hospitalizados"',
          'O tema deve ser pesquisável — verifique se há literatura disponível',
          'Delimite por: população, local, período, aspecto específico',
        ],
        elementos_obrigatorios: ['tema geral', 'delimitação', 'justificativa da escolha'],
        erros_comuns: ['Tema muito amplo', 'Tema sem literatura suficiente', 'Tema já exaustivamente estudado sem nova perspectiva'],
        min_palavras: 200,
        max_palavras: 500,
      },
      {
        id: 'problema',
        chave_secao: 'problema',
        nome: 'Problema e Hipótese',
        descricao: 'Formule a pergunta de pesquisa e a hipótese',
        obrigatoria: true,
        tempo_estimado_minutos: 15,
        instrucoes: 'A pergunta de pesquisa deve ser clara, específica e respondível. A hipótese é sua resposta provisória.',
        dicas_ia: [
          'Use o formato: "Qual o efeito de X sobre Y em Z?"',
          'A hipótese deve ser testável e falsificável',
          'Diferencie hipótese nula (H0) de hipótese alternativa (H1)',
        ],
        elementos_obrigatorios: ['pergunta de pesquisa', 'hipótese', 'variáveis'],
        erros_comuns: ['Pergunta muito vaga', 'Hipótese não testável', 'Múltiplas perguntas misturadas'],
        min_palavras: 150,
        max_palavras: 400,
      },
      {
        id: 'objetivos',
        chave_secao: 'objetivos',
        nome: 'Objetivos',
        descricao: 'Defina o objetivo geral e os específicos',
        obrigatoria: true,
        tempo_estimado_minutos: 10,
        instrucoes: 'O objetivo geral responde diretamente à pergunta de pesquisa. Os específicos são os passos para alcançá-lo.',
        dicas_ia: [
          'Inicie com verbos no infinitivo: analisar, comparar, identificar, avaliar',
          'Objetivo geral: 1 frase, alinhado à pergunta de pesquisa',
          'Objetivos específicos: 3-5, cada um mensurável',
        ],
        elementos_obrigatorios: ['objetivo geral', 'objetivos específicos (mín. 3)'],
        erros_comuns: ['Objetivo igual ao título', 'Objetivos não mensuráveis', 'Confundir objetivo com metodologia'],
        min_palavras: 100,
        max_palavras: 300,
      },
      {
        id: 'justificativa',
        chave_secao: 'justificativa',
        nome: 'Justificativa',
        descricao: 'Por que este trabalho é importante?',
        obrigatoria: true,
        tempo_estimado_minutos: 15,
        instrucoes: 'Argumente a relevância científica, social e/ou prática do trabalho. Mostre a lacuna de conhecimento.',
        dicas_ia: [
          'Responda: "Por que estudar isso agora?"',
          'Cite dados epidemiológicos ou estatísticas relevantes',
          'Identifique a lacuna na literatura que seu trabalho preenche',
        ],
        elementos_obrigatorios: ['relevância científica', 'relevância social/prática', 'lacuna de conhecimento'],
        erros_comuns: ['Justificativa muito genérica', 'Sem dados concretos', 'Confundir justificativa com objetivos'],
        min_palavras: 300,
        max_palavras: 600,
      },
      {
        id: 'revisao_literatura',
        chave_secao: 'revisao_literatura',
        nome: 'Revisão de Literatura',
        descricao: 'Síntese crítica do conhecimento existente',
        obrigatoria: true,
        tempo_estimado_minutos: 60,
        instrucoes: 'Apresente o estado da arte sobre o tema. Organize por subtemas. Use fontes dos últimos 5-10 anos preferencialmente.',
        dicas_ia: [
          'Não é resumo de artigos — é síntese crítica',
          'Organize por subtemas, não por artigo',
          'Mostre concordâncias e divergências na literatura',
          'Todas as afirmações precisam de citação',
        ],
        elementos_obrigatorios: ['contextualização do tema', 'revisão dos estudos relevantes', 'síntese crítica'],
        erros_comuns: ['Resumir artigos individualmente', 'Usar apenas fontes antigas', 'Copiar textos sem síntese própria'],
        min_palavras: 1500,
        max_palavras: 4000,
      },
      {
        id: 'referencial_teorico',
        chave_secao: 'referencial_teorico',
        nome: 'Referencial Teórico',
        descricao: 'Base conceitual que sustenta o trabalho',
        obrigatoria: false,
        tempo_estimado_minutos: 30,
        instrucoes: 'Apresente as teorias, conceitos e modelos que fundamentam sua pesquisa.',
        dicas_ia: [
          'Diferencie do que é revisão de literatura — aqui são os conceitos-base',
          'Cite os autores fundadores das teorias usadas',
          'Explique como cada conceito se relaciona com seu trabalho',
        ],
        elementos_obrigatorios: ['teorias base', 'conceitos-chave', 'relação com o trabalho'],
        erros_comuns: ['Confundir com revisão de literatura', 'Teorias sem relação com o trabalho'],
        min_palavras: 500,
        max_palavras: 2000,
      },
      {
        id: 'metodologia',
        chave_secao: 'metodologia',
        nome: 'Metodologia',
        descricao: 'Como a pesquisa foi ou será realizada',
        obrigatoria: true,
        tempo_estimado_minutos: 30,
        instrucoes: 'Descreva o tipo de estudo, população, amostra, instrumentos, coleta e análise de dados com detalhes suficientes para replicação.',
        dicas_ia: [
          'Tipo de estudo: quantitativo, qualitativo ou misto',
          'Delineamento: experimental, observacional, descritivo, etc.',
          'Amostragem: probabilística ou não-probabilística (justifique)',
          'Análise: software estatístico, nível de significância',
        ],
        elementos_obrigatorios: ['tipo e delineamento', 'população e amostra', 'critérios de inclusão/exclusão', 'instrumentos', 'análise de dados'],
        erros_comuns: ['Metodologia vaga', 'Sem justificativa da amostra', 'Não mencionar aspectos éticos'],
        min_palavras: 500,
        max_palavras: 1500,
      },
      {
        id: 'resultados',
        chave_secao: 'resultados',
        nome: 'Resultados',
        descricao: 'Apresentação dos dados obtidos',
        obrigatoria: true,
        tempo_estimado_minutos: 30,
        instrucoes: 'Apresente os resultados de forma objetiva, sem interpretação. Use tabelas e figuras quando necessário.',
        dicas_ia: [
          'Resultados: apenas o que foi encontrado, sem opinião',
          'Descreva tabelas e figuras no texto (não apenas "veja tabela 1")',
          'Use estatística descritiva antes da inferencial',
        ],
        elementos_obrigatorios: ['caracterização da amostra', 'resultados principais', 'dados estatísticos'],
        erros_comuns: ['Misturar resultados com discussão', 'Não descrever tabelas no texto', 'Omitir dados negativos'],
        min_palavras: 500,
        max_palavras: 2000,
      },
      {
        id: 'discussao',
        chave_secao: 'discussao',
        nome: 'Discussão',
        descricao: 'Interpretação e comparação com a literatura',
        obrigatoria: true,
        tempo_estimado_minutos: 30,
        instrucoes: 'Interprete seus resultados à luz da literatura. Compare com estudos similares. Explique concordâncias e divergências.',
        dicas_ia: [
          'Responda: "O que esses resultados significam?"',
          'Compare com estudos da revisão de literatura',
          'Explique resultados inesperados',
          'Mencione as limitações do estudo',
        ],
        elementos_obrigatorios: ['interpretação dos resultados', 'comparação com literatura', 'limitações do estudo'],
        erros_comuns: ['Repetir os resultados', 'Não citar literatura na discussão', 'Omitir limitações'],
        min_palavras: 500,
        max_palavras: 2000,
      },
      {
        id: 'conclusao',
        chave_secao: 'conclusao',
        nome: 'Conclusão',
        descricao: 'Síntese e respostas aos objetivos',
        obrigatoria: true,
        tempo_estimado_minutos: 15,
        instrucoes: 'Retome cada objetivo e informe se foi alcançado. Aponte contribuições e sugestões para estudos futuros.',
        dicas_ia: [
          'A conclusão deve responder diretamente à pergunta de pesquisa',
          'Retome cada objetivo específico',
          'Não introduza dados novos aqui',
          'Finalize com recomendações práticas e/ou para pesquisas futuras',
        ],
        elementos_obrigatorios: ['resposta à pergunta de pesquisa', 'alcance dos objetivos', 'contribuições', 'recomendações'],
        erros_comuns: ['Introduzir dados novos', 'Conclusão igual ao resumo', 'Muito longa com repetições'],
        min_palavras: 200,
        max_palavras: 600,
      },
      {
        id: 'resumo',
        chave_secao: 'resumo',
        nome: 'Resumo e Abstract',
        descricao: 'Síntese estruturada em português e inglês',
        obrigatoria: true,
        tempo_estimado_minutos: 20,
        instrucoes: 'O resumo deve conter: contexto, objetivo, método, resultado e conclusão. Entre 150-500 palavras (ABNT NBR 6028).',
        dicas_ia: [
          'Escreva o resumo por último — após concluir o trabalho',
          'Estrutura: contexto (1-2 frases) → objetivo → método → resultado → conclusão',
          'Abstract: não é tradução literal, é reescrita em inglês acadêmico',
          'Keywords: 3-6 termos, preferencialmente MeSH/DeCS',
        ],
        elementos_obrigatorios: ['contextualização', 'objetivo', 'método', 'resultados', 'conclusão', 'palavras-chave'],
        erros_comuns: ['Resumo muito longo ou curto', 'Abstract como tradução literal', 'Palavras-chave genéricas'],
        min_palavras: 150,
        max_palavras: 500,
      },
      {
        id: 'introducao',
        chave_secao: 'introducao',
        nome: 'Introdução',
        descricao: 'Contextualização e apresentação do trabalho',
        obrigatoria: true,
        tempo_estimado_minutos: 20,
        instrucoes: 'A introdução é escrita por último mas aparece primeiro. Contextualize o tema, apresente o problema, os objetivos e a estrutura do trabalho.',
        dicas_ia: [
          'Escreva após concluir as demais seções',
          'Estrutura clássica: funil — do geral para o específico',
          'Finalize com: "Este trabalho está organizado em X capítulos..."',
          'Não repita o resumo — seja mais narrativo e contextual',
        ],
        elementos_obrigatorios: ['contextualização', 'problema de pesquisa', 'objetivos', 'estrutura do trabalho'],
        erros_comuns: ['Escrever antes de concluir o trabalho', 'Muito longa', 'Repetir o resumo'],
        min_palavras: 400,
        max_palavras: 1000,
      },
    ],
  },

  artigo_original: {
    tipo: 'artigo_original',
    nome_completo: 'Artigo Científico Original',
    descricao: 'Para publicação em periódicos científicos.',
    nivel: ['graduacao', 'especializacao', 'mestrado', 'doutorado', 'professor'],
    duracao_estimada_horas: 10,
    requer_cep: false,
    requer_prisma: false,
    formatos_citacao_recomendados: ['vancouver', 'abnt', 'apa'],
    fases: [
      { id: 'pico', chave_secao: 'pico', nome: 'Pergunta PICO', descricao: 'Estruture a pergunta de pesquisa', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Use o framework PICO: Paciente/Problema, Intervenção, Comparação, Outcome (desfecho).', dicas_ia: ['P: Quem? (população específica)', 'I: O quê? (intervenção/exposição)', 'C: Comparado a quê?', 'O: Com qual desfecho?'], elementos_obrigatorios: ['P', 'I', 'C', 'O'], erros_comuns: ['PICO incompleto', 'Desfecho vago'], min_palavras: 100, max_palavras: 300 },
      { id: 'titulo', chave_secao: 'titulo', nome: 'Título', descricao: 'Título informativo e preciso', obrigatoria: true, tempo_estimado_minutos: 10, instrucoes: 'O título deve identificar claramente o desenho do estudo, a população e o desfecho.', dicas_ia: ['Máximo 15 palavras', 'Inclua: tipo de estudo, população, desfecho', 'Evite abreviações'], elementos_obrigatorios: ['tema principal', 'tipo de estudo (se relevante)'], erros_comuns: ['Título vago', 'Muito longo', 'Abreviações'], min_palavras: 5, max_palavras: 25 },
      { id: 'introducao', chave_secao: 'introducao', nome: 'Introdução', descricao: 'Contexto e justificativa do artigo', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Em 3-5 parágrafos: contextualize o problema, apresente a lacuna do conhecimento e o objetivo do estudo.', dicas_ia: ['Último parágrafo: "O objetivo deste estudo foi..."', 'Cite dados epidemiológicos atuais', 'Máximo 400 palavras para periódicos'], elementos_obrigatorios: ['contexto', 'lacuna', 'objetivo'], erros_comuns: ['Muito longa', 'Sem lacuna clara', 'Objetivo ausente'], min_palavras: 200, max_palavras: 500 },
      { id: 'metodos_delineamento', chave_secao: 'metodos_delineamento', nome: 'Métodos — Delineamento', descricao: 'Tipo de estudo e população', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Descreva o delineamento, local, período, população, amostragem e critérios de seleção.', dicas_ia: ['Declare o tipo de estudo na primeira frase', 'Mencione aprovação do CEP se houver', 'CONSORT para ECR, STROBE para observacionais'], elementos_obrigatorios: ['delineamento', 'local/período', 'população', 'amostragem', 'critérios'], erros_comuns: ['Delineamento impreciso', 'Critérios vagos'], min_palavras: 200, max_palavras: 600 },
      { id: 'metodos_coleta', chave_secao: 'metodos_coleta', nome: 'Métodos — Coleta e Análise', descricao: 'Instrumentos, procedimentos e análise estatística', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Descreva os instrumentos de coleta, procedimentos e análise estatística com software e nível de significância.', dicas_ia: ['Seja reprodutível: outro pesquisador deve conseguir repetir', 'Mencione o software estatístico (R, SPSS, Stata)', 'Declare o α adotado (geralmente 0,05)'], elementos_obrigatorios: ['instrumentos', 'procedimentos', 'análise estatística'], erros_comuns: ['Análise não descrita', 'Software não mencionado'], min_palavras: 200, max_palavras: 600 },
      { id: 'resultados', chave_secao: 'resultados', nome: 'Resultados', descricao: 'Dados obtidos sem interpretação', obrigatoria: true, tempo_estimado_minutos: 25, instrucoes: 'Apresente os resultados seguindo a ordem dos objetivos. Use tabelas e figuras. Descreva-as no texto.', dicas_ia: ['Sem interpretação aqui — apenas dados', 'Tabela 1: sempre caracterização da amostra', 'IC 95% e valor-p para inferências'], elementos_obrigatorios: ['caracterização amostral', 'desfecho primário', 'desfechos secundários'], erros_comuns: ['Interpretar na seção de resultados', 'Não descrever tabelas'], min_palavras: 300, max_palavras: 1200 },
      { id: 'discussao', chave_secao: 'discussao', nome: 'Discussão', descricao: 'Interpretação e contextualização', obrigatoria: true, tempo_estimado_minutos: 30, instrucoes: 'Inicie com o achado principal. Compare com a literatura. Explique mecanismos. Declare limitações.', dicas_ia: ['1º parágrafo: achado principal em 1-2 frases', 'Compare com estudos similares (citar)', 'Penúltimo parágrafo: limitações', 'Último: implicações clínicas/práticas'], elementos_obrigatorios: ['achado principal', 'comparação com literatura', 'limitações', 'implicações'], erros_comuns: ['Repetir resultados', 'Sem limitações', 'Discussão especulativa demais'], min_palavras: 400, max_palavras: 1500 },
      { id: 'conclusao', chave_secao: 'conclusao', nome: 'Conclusão', descricao: 'Resposta objetiva à pergunta de pesquisa', obrigatoria: true, tempo_estimado_minutos: 10, instrucoes: 'Em 1-3 parágrafos ou até 150 palavras: responda à pergunta de pesquisa e aponte recomendações.', dicas_ia: ['Seja direto e objetivo', 'Não repita discussão', 'Inclua recomendação para prática ou pesquisa futura'], elementos_obrigatorios: ['resposta à pergunta', 'recomendação'], erros_comuns: ['Muito longa', 'Dados novos', 'Generalizações excessivas'], min_palavras: 50, max_palavras: 200 },
      { id: 'resumo', chave_secao: 'resumo', nome: 'Resumo Estruturado', descricao: 'Resumo com seções definidas + abstract', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Resumo estruturado com cabeçalhos: Objetivo, Métodos, Resultados, Conclusão. Geralmente 250 palavras.', dicas_ia: ['Escreva após concluir o artigo', 'Cada seção: 1-3 frases concisas', 'Abstract: inglês acadêmico fluente, não tradução literal'], elementos_obrigatorios: ['objetivo', 'métodos', 'resultados', 'conclusão', 'palavras-chave'], erros_comuns: ['Ultrapassar o limite do periódico', 'Abstract como tradução'], min_palavras: 150, max_palavras: 350 },
      { id: 'carta_submissao', chave_secao: 'carta_submissao', nome: 'Carta de Submissão', descricao: 'Cover letter para o editor', obrigatoria: false, tempo_estimado_minutos: 10, instrucoes: 'Carta ao editor explicando por que o artigo é adequado para o periódico e qual a contribuição principal.', dicas_ia: ['Personalize para o periódico alvo', 'Destaque a novidade do estudo', 'Máximo 1 página', 'Declare conflitos de interesse'], elementos_obrigatorios: ['periódico alvo', 'contribuição principal', 'declarações obrigatórias'], erros_comuns: ['Carta genérica', 'Muito longa'], min_palavras: 150, max_palavras: 400 },
    ],
  },

  revisao_sistematica: {
    tipo: 'revisao_sistematica',
    nome_completo: 'Revisão Sistemática',
    descricao: 'Metodologia rigorosa com PRISMA. Inclui diagrama de fluxo e análise de viés.',
    nivel: ['especializacao', 'mestrado', 'doutorado', 'professor'],
    duracao_estimada_horas: 40,
    requer_cep: false,
    requer_prisma: true,
    formatos_citacao_recomendados: ['vancouver', 'abnt'],
    fases: [
      { id: 'protocolo', chave_secao: 'protocolo', nome: 'Protocolo PROSPERO', descricao: 'Registro do protocolo da revisão', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Registre o protocolo no PROSPERO antes de iniciar a busca. Inclua: pergunta, critérios, estratégia de busca.', dicas_ia: ['Registro no PROSPERO é padrão ouro', 'Cite o número de registro no artigo', 'Protocolo deve ser público antes da busca'], elementos_obrigatorios: ['questão de pesquisa', 'critérios PICOS', 'bases a pesquisar', 'análise planejada'], erros_comuns: ['Não registrar antes de começar', 'Protocolo vago'], min_palavras: 200, max_palavras: 500 },
      { id: 'pergunta_pico', chave_secao: 'pergunta_pico', nome: 'Pergunta PICO/PICOS', descricao: 'Estrutura a pergunta de pesquisa', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Formule a pergunta usando PICOS: P (população), I (intervenção), C (comparação), O (desfecho), S (tipo de estudo).', dicas_ia: ['Seja específico em cada elemento', 'O S define os tipos de estudos elegíveis', 'A pergunta guia todos os critérios'], elementos_obrigatorios: ['P', 'I', 'C', 'O', 'S'], erros_comuns: ['PICO incompleto', 'Pergunta muito abrangente'], min_palavras: 150, max_palavras: 400 },
      { id: 'estrategia_busca', chave_secao: 'estrategia_busca', nome: 'Estratégia de Busca', descricao: 'Strings de busca para cada base', obrigatoria: true, tempo_estimado_minutos: 60, instrucoes: 'Desenvolva estratégias de busca sensíveis e específicas para cada base de dados. Use MeSH/DeCS e operadores booleanos.', dicas_ia: ['PubMed: use MeSH terms + keywords livres', 'EMBASE: use Emtree', 'LILACS: use DeCS (em português)', 'Combine com OR termos similares, AND os elementos PICO'], elementos_obrigatorios: ['estratégia por base', 'termos MeSH/DeCS', 'operadores booleanos', 'filtros aplicados'], erros_comuns: ['Busca pouco sensível', 'Não documentar a estratégia completa'], min_palavras: 300, max_palavras: 800 },
      { id: 'criterios', chave_secao: 'criterios', nome: 'Critérios de Elegibilidade', descricao: 'Inclusão e exclusão dos estudos', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Defina critérios claros de inclusão e exclusão baseados no PICOS. Aplicados de forma independente por 2 revisores.', dicas_ia: ['Critérios devem ser objetivos e verificáveis', '2 revisores independentes — calcular concordância (Kappa)', 'Desempate: terceiro revisor'], elementos_obrigatorios: ['critérios de inclusão', 'critérios de exclusão', 'processo de triagem'], erros_comuns: ['Critérios subjetivos', 'Aplicação por apenas 1 revisor'], min_palavras: 200, max_palavras: 500 },
      { id: 'triagem_prisma', chave_secao: 'triagem_prisma', nome: 'Triagem e Diagrama PRISMA', descricao: 'Fluxo de seleção dos estudos', obrigatoria: true, tempo_estimado_minutos: 30, instrucoes: 'Registre cada etapa do fluxo: identificação, triagem, elegibilidade e inclusão. Gere o diagrama PRISMA 2020.', dicas_ia: ['PRISMA 2020 substituiu o 2009', 'Documente motivos de exclusão na elegibilidade', 'Números devem ser exatos e auditáveis'], elementos_obrigatorios: ['números por etapa', 'motivos de exclusão', 'diagrama PRISMA'], erros_comuns: ['Números inconsistentes', 'Motivos de exclusão vagos'], min_palavras: 150, max_palavras: 400 },
      { id: 'extracao_dados', chave_secao: 'extracao_dados', nome: 'Extração de Dados', descricao: 'Coleta padronizada dos dados dos estudos', obrigatoria: true, tempo_estimado_minutos: 40, instrucoes: 'Use formulário padronizado. Extraia: autores, ano, local, N, delineamento, intervenção, desfechos, resultados.', dicas_ia: ['2 revisores independentes também na extração', 'Pilote o formulário nos primeiros 5 estudos', 'Contate autores para dados faltantes'], elementos_obrigatorios: ['formulário de extração', 'dados extraídos', 'tabela de características dos estudos'], erros_comuns: ['Extração incompleta', 'Dados inconsistentes entre revisores'], min_palavras: 200, max_palavras: 600 },
      { id: 'risco_vies', chave_secao: 'risco_vies', nome: 'Avaliação de Risco de Viés', descricao: 'Qualidade metodológica dos estudos incluídos', obrigatoria: true, tempo_estimado_minutos: 40, instrucoes: 'Use ferramentas validadas: RoB 2.0 (ECR), ROBINS-I (observacionais), QUADAS-2 (diagnóstico).', dicas_ia: ['Escolha a ferramenta adequada ao tipo de estudo', '2 avaliadores independentes', 'Apresente em tabela/figura resumo'], elementos_obrigatorios: ['ferramenta utilizada', 'avaliação por domínio', 'julgamento geral'], erros_comuns: ['Usar ferramenta inadequada', 'Não justificar os julgamentos'], min_palavras: 200, max_palavras: 500 },
      { id: 'sintese', chave_secao: 'sintese', nome: 'Síntese Qualitativa', descricao: 'Narrativa integrativa dos resultados', obrigatoria: true, tempo_estimado_minutos: 30, instrucoes: 'Sintetize os resultados de forma narrativa. Use tabelas. Se heterogeneidade impedir meta-análise, justifique.', dicas_ia: ['Agrupe estudos por desfecho e população', 'Não apenas descreva — sintetize e compare', 'Avalie heterogeneidade clínica e metodológica'], elementos_obrigatorios: ['síntese por desfecho', 'heterogeneidade', 'tabela de resultados'], erros_comuns: ['Apenas descrever estudos', 'Ignorar heterogeneidade'], min_palavras: 500, max_palavras: 2000 },
      { id: 'metanalise', chave_secao: 'metanalise', nome: 'Meta-análise', descricao: 'Síntese quantitativa (se aplicável)', obrigatoria: false, tempo_estimado_minutos: 60, instrucoes: 'Realize meta-análise quando estudos forem homogêneos. Calcule tamanho de efeito com IC 95%. Forest plot.', dicas_ia: ['I² < 25%: homogêneo, modelo efeito fixo', 'I² > 75%: heterogêneo, evitar ou modelo aleatório', 'Funnel plot para viés de publicação (≥10 estudos)'], elementos_obrigatorios: ['modelo estatístico', 'tamanho de efeito', 'forest plot', 'análise de sensibilidade'], erros_comuns: ['Meta-análise com estudos heterogêneos', 'Sem análise de sensibilidade'], min_palavras: 300, max_palavras: 1000 },
      { id: 'discussao', chave_secao: 'discussao', nome: 'Discussão e GRADE', descricao: 'Interpretação e qualidade das evidências', obrigatoria: true, tempo_estimado_minutos: 30, instrucoes: 'Interprete os achados. Aplique o framework GRADE para avaliar a certeza das evidências.', dicas_ia: ['GRADE: certeza muito baixa → baixa → moderada → alta', 'Limitações da revisão (diferentes das dos estudos)', 'Implicações para prática e pesquisa'], elementos_obrigatorios: ['interpretação', 'avaliação GRADE', 'limitações da revisão', 'implicações'], erros_comuns: ['Não usar GRADE', 'Confundir limitações dos estudos com da revisão'], min_palavras: 400, max_palavras: 1500 },
      { id: 'conclusao', chave_secao: 'conclusao', nome: 'Conclusão', descricao: 'Síntese final e recomendações', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Responda à pergunta de pesquisa com base na certeza das evidências (GRADE). Recomendações para prática e pesquisa.', dicas_ia: ['Seja prudente — a certeza das evidências guia a força das conclusões', 'Não afirme mais do que os dados permitem'], elementos_obrigatorios: ['resposta à pergunta', 'recomendações baseadas em certeza'], erros_comuns: ['Conclusões mais fortes que as evidências permitem'], min_palavras: 150, max_palavras: 400 },
      { id: 'resumo', chave_secao: 'resumo', nome: 'Resumo Estruturado', descricao: 'Resumo + abstract da revisão sistemática', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Seguir o formato do periódico alvo. Geralmente: Contexto, Objetivo, Fontes, Seleção, Extração, Resultados, Limitações, Conclusões.', dicas_ia: ['Mencione o número de estudos incluídos', 'Cite o desfecho principal com dados', 'Mencione a certeza das evidências (GRADE)'], elementos_obrigatorios: ['contexto', 'métodos', 'resultados', 'certeza das evidências', 'conclusão'], erros_comuns: ['Não mencionar GRADE no resumo', 'Resumo incompleto'], min_palavras: 200, max_palavras: 400 },
    ],
  },

  projeto_pesquisa: {
    tipo: 'projeto_pesquisa',
    nome_completo: 'Projeto de Pesquisa',
    descricao: 'Proposta estruturada para editais, bolsas ou início de pós-graduação.',
    nivel: ['graduacao', 'especializacao', 'mestrado', 'doutorado', 'professor'],
    duracao_estimada_horas: 8,
    requer_cep: false,
    requer_prisma: false,
    formatos_citacao_recomendados: ['abnt', 'vancouver', 'apa'],
    fases: [
      { id: 'tema', chave_secao: 'tema', nome: 'Tema e Problema', descricao: 'Definição do tema e problema de pesquisa', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Apresente o tema, a problematização e a pergunta de pesquisa central.', dicas_ia: ['Mostre que o tema é relevante e viável', 'A pergunta deve ser específica e respondível', 'Conecte ao contexto atual'], elementos_obrigatorios: ['tema', 'problema', 'pergunta de pesquisa'], erros_comuns: ['Tema vago', 'Problema não pesquisável'], min_palavras: 300, max_palavras: 600 },
      { id: 'objetivos', chave_secao: 'objetivos', nome: 'Objetivos e Hipóteses', descricao: 'O que o projeto pretende alcançar', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Defina objetivo geral, objetivos específicos (3-5) e hipóteses quando aplicável.', dicas_ia: ['Verbos mensuráveis: analisar, comparar, identificar', 'Objetivos específicos = etapas para o objetivo geral'], elementos_obrigatorios: ['objetivo geral', 'objetivos específicos', 'hipóteses'], erros_comuns: ['Objetivos não mensuráveis', 'Muitos objetivos'], min_palavras: 150, max_palavras: 400 },
      { id: 'justificativa', chave_secao: 'justificativa', nome: 'Justificativa e Relevância', descricao: 'Por que o projeto deve ser financiado/aprovado', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Argumente a relevância científica, social, econômica ou política. Mostre a lacuna de conhecimento.', dicas_ia: ['Para editais: alinhe à área prioritária do edital', 'Cite dados que justifiquem a urgência', 'Mostre quem se beneficiará dos resultados'], elementos_obrigatorios: ['relevância científica', 'relevância social', 'lacuna de conhecimento', 'beneficiários'], erros_comuns: ['Muito genérica', 'Sem dados concretos', 'Não alinhada ao edital'], min_palavras: 400, max_palavras: 800 },
      { id: 'revisao_literatura', chave_secao: 'revisao_literatura', nome: 'Revisão de Literatura', descricao: 'Estado da arte sobre o tema', obrigatoria: true, tempo_estimado_minutos: 40, instrucoes: 'Mostre o que já se sabe e identifique claramente a lacuna que seu projeto pretende preencher.', dicas_ia: ['Foco na lacuna — não é revisão completa, mas suficiente para justificar o projeto', 'Organize por subtemas', 'Priorize publicações dos últimos 5 anos'], elementos_obrigatorios: ['estado da arte', 'lacuna identificada', 'referências atualizadas'], erros_comuns: ['Revisão muito superficial', 'Lacuna não evidente'], min_palavras: 600, max_palavras: 2000 },
      { id: 'metodologia', chave_secao: 'metodologia', nome: 'Metodologia', descricao: 'Como o projeto será executado', obrigatoria: true, tempo_estimado_minutos: 30, instrucoes: 'Descreva o delineamento, local, população, amostra, instrumentos, coleta e análise de dados.', dicas_ia: ['Seja detalhado o suficiente para avaliar a viabilidade', 'Inclua o tamanho amostral com cálculo', 'Mencione os procedimentos de controle de qualidade'], elementos_obrigatorios: ['delineamento', 'local', 'população/amostra', 'instrumentos', 'análise'], erros_comuns: ['Metodologia vaga', 'Sem cálculo amostral', 'Sem análise estatística descrita'], min_palavras: 500, max_palavras: 1500 },
      { id: 'aspectos_eticos', chave_secao: 'aspectos_eticos', nome: 'Aspectos Éticos', descricao: 'Conformidade ética da pesquisa', obrigatoria: false, tempo_estimado_minutos: 15, instrucoes: 'Declare se a pesquisa envolve seres humanos/animais e os procedimentos éticos adotados.', dicas_ia: ['Se envolve seres humanos: mencionar submissão ao CEP', 'Resolução CNS 466/2012 (humanos) ou 580/2018 (animais)', 'Declare sigilo, confidencialidade e direito de retirada'], elementos_obrigatorios: ['tipo de pesquisa quanto à ética', 'procedimentos éticos', 'submissão ao CEP se necessário'], erros_comuns: ['Omitir aspectos éticos em pesquisa com humanos'], min_palavras: 100, max_palavras: 400 },
      { id: 'cronograma', chave_secao: 'cronograma', nome: 'Cronograma', descricao: 'Planejamento temporal das atividades', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Liste as atividades do projeto com meses ou trimestres de execução. Formato de tabela.', dicas_ia: ['Atividades realistas dentro do prazo do projeto', 'Inclua: revisão de literatura, coleta, análise, escrita, submissão', 'Deixe margem para imprevistos'], elementos_obrigatorios: ['atividades', 'período de execução', 'responsáveis'], erros_comuns: ['Cronograma irrealista', 'Fases importantes omitidas'], min_palavras: 100, max_palavras: 400 },
      { id: 'orcamento', chave_secao: 'orcamento', nome: 'Orçamento e Recursos', descricao: 'Previsão de custos e recursos necessários', obrigatoria: false, tempo_estimado_minutos: 15, instrucoes: 'Detalhe os recursos humanos, materiais e financeiros necessários. Justifique cada item.', dicas_ia: ['Para editais: siga as rubricas permitidas', 'Justifique cada item de custo', 'Inclua infraestrutura disponível na instituição'], elementos_obrigatorios: ['recursos humanos', 'materiais', 'custos estimados', 'justificativas'], erros_comuns: ['Orçamento sem justificativa', 'Itens não permitidos pelo edital'], min_palavras: 150, max_palavras: 600 },
      { id: 'resultados_esperados', chave_secao: 'resultados_esperados', nome: 'Resultados Esperados e Impacto', descricao: 'O que o projeto vai produzir e qual o impacto', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Descreva os produtos do projeto (artigos, relatórios, protocolos) e o impacto esperado.', dicas_ia: ['Seja específico: "2 artigos em periódicos Qualis A"', 'Impacto: científico, social, econômico, político', 'Para editais de inovação: mencionar potencial de transferência de tecnologia'], elementos_obrigatorios: ['produtos', 'impacto científico', 'impacto social', 'disseminação'], erros_comuns: ['Resultados vagos', 'Sem produtos concretos'], min_palavras: 200, max_palavras: 500 },
    ],
  },

  relatorio_ic: {
    tipo: 'relatorio_ic',
    nome_completo: 'Relatório de Iniciação Científica',
    descricao: 'Relatório de atividades de IC/PIBIC.',
    nivel: ['graduacao'],
    duracao_estimada_horas: 6,
    requer_cep: false,
    requer_prisma: false,
    formatos_citacao_recomendados: ['abnt'],
    fases: [
      { id: 'resumo_atividades', chave_secao: 'resumo_atividades', nome: 'Resumo das Atividades', descricao: 'Síntese das atividades do período', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Resuma as principais atividades realizadas no período de IC com resultados preliminares.', dicas_ia: ['Seja objetivo e factual', 'Mencione o que foi planejado vs. realizado', 'Destaque os principais aprendizados'], elementos_obrigatorios: ['período', 'atividades realizadas', 'resultados preliminares'], erros_comuns: ['Muito vago', 'Sem resultados mencionados'], min_palavras: 150, max_palavras: 400 },
      { id: 'introducao', chave_secao: 'introducao', nome: 'Introdução e Contextualização', descricao: 'Contexto do projeto de IC', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Contextualize o projeto de pesquisa e o problema investigado durante a IC.', dicas_ia: ['Baseie-se no projeto aprovado', 'Contextualize a relevância do tema', 'Apresente o objetivo geral da IC'], elementos_obrigatorios: ['contexto', 'problema', 'objetivo da IC'], erros_comuns: ['Repetir o projeto original sem adaptação'], min_palavras: 300, max_palavras: 700 },
      { id: 'objetivos', chave_secao: 'objetivos', nome: 'Objetivos do Período', descricao: 'O que foi planejado alcançar', obrigatoria: true, tempo_estimado_minutos: 10, instrucoes: 'Liste os objetivos planejados para o período e indique o grau de alcance de cada um.', dicas_ia: ['Compare com o plano de trabalho original', 'Justifique objetivos não alcançados'], elementos_obrigatorios: ['objetivos planejados', 'grau de alcance'], erros_comuns: ['Não alinhar com o plano de trabalho'], min_palavras: 100, max_palavras: 300 },
      { id: 'metodologia', chave_secao: 'metodologia', nome: 'Metodologia Utilizada', descricao: 'Métodos empregados nas atividades', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Descreva os métodos utilizados nas atividades do período com o suficiente para compreender o que foi feito.', dicas_ia: ['Seja específico: quais procedimentos, quais instrumentos', 'Mencione adaptações metodológicas se houve'], elementos_obrigatorios: ['métodos utilizados', 'instrumentos', 'procedimentos'], erros_comuns: ['Muito genérico', 'Sem detalhe suficiente'], min_palavras: 200, max_palavras: 600 },
      { id: 'resultados', chave_secao: 'resultados', nome: 'Resultados Obtidos', descricao: 'O que foi alcançado no período', obrigatoria: true, tempo_estimado_minutos: 25, instrucoes: 'Apresente os resultados obtidos, mesmo que preliminares. Use tabelas e figuras quando pertinente.', dicas_ia: ['Resultados parciais também são válidos', 'Apresente dados, não apenas descrições qualitativas', 'Compare com o esperado no plano de trabalho'], elementos_obrigatorios: ['resultados obtidos', 'dados', 'comparação com expectativas'], erros_comuns: ['Muito vago', 'Sem dados concretos'], min_palavras: 300, max_palavras: 1000 },
      { id: 'dificuldades', chave_secao: 'dificuldades', nome: 'Dificuldades e Soluções', descricao: 'Obstáculos e como foram superados', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Relate dificuldades encontradas e as soluções adotadas ou planejadas.', dicas_ia: ['Seja honesto — dificuldades são esperadas e valorizadas pelos avaliadores', 'Para cada dificuldade, apresente uma solução ou encaminhamento'], elementos_obrigatorios: ['dificuldades', 'soluções adotadas', 'encaminhamentos'], erros_comuns: ['Omitir dificuldades', 'Sem proposta de solução'], min_palavras: 150, max_palavras: 400 },
      { id: 'formacao', chave_secao: 'formacao', nome: 'Atividades de Formação', descricao: 'Cursos, eventos e publicações do período', obrigatoria: true, tempo_estimado_minutos: 10, instrucoes: 'Liste participações em eventos, cursos, disciplinas, publicações e apresentações do período.', dicas_ia: ['Apresentações em congressos são especialmente valorizadas', 'Inclua: congressos, minicursos, disciplinas cursadas, publicações'], elementos_obrigatorios: ['eventos', 'cursos', 'publicações/apresentações'], erros_comuns: ['Seção vazia — sempre há algo a registrar'], min_palavras: 100, max_palavras: 400 },
      { id: 'perspectivas', chave_secao: 'perspectivas', nome: 'Perspectivas e Próximas Etapas', descricao: 'Planejamento para o próximo período', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Descreva as atividades planejadas para o próximo período e as perspectivas de conclusão do projeto.', dicas_ia: ['Seja realista com base no cronograma original', 'Mencione perspectivas de publicação', 'Conecte com os objetivos ainda não alcançados'], elementos_obrigatorios: ['próximas atividades', 'cronograma', 'perspectivas de conclusão'], erros_comuns: ['Plano vago', 'Sem conexão com objetivos'], min_palavras: 150, max_palavras: 400 },
    ],
  },

  dissertacao_mestrado: {
    tipo: 'dissertacao_mestrado',
    nome_completo: 'Dissertação de Mestrado',
    descricao: 'Trabalho de pesquisa original seguindo normas da sua instituição.',
    nivel: ['mestrado'],
    duracao_estimada_horas: 60,
    requer_cep: false,
    requer_prisma: false,
    formatos_citacao_recomendados: ['abnt', 'vancouver', 'apa'],
    fases: [
      { id: 'tema', chave_secao: 'tema', nome: 'Tema, Lacuna e Originalidade', descricao: 'Identifique a lacuna de conhecimento', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Apresente o tema com delimitação clara, identifique a lacuna no conhecimento e justifique a originalidade da proposta.', dicas_ia: ['A originalidade é critério de avaliação da CAPES', 'Mostre o que a literatura não respondeu ainda', 'A lacuna deve ser evidente e relevante'], elementos_obrigatorios: ['tema', 'lacuna identificada', 'contribuição original'], erros_comuns: ['Tema sem originalidade', 'Lacuna não demonstrada'], min_palavras: 400, max_palavras: 800 },
      { id: 'problema', chave_secao: 'problema', nome: 'Problema e Hipóteses', descricao: 'Pergunta e respostas provisórias', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Formule a pergunta de pesquisa central e as hipóteses (nula e alternativa) que serão testadas.', dicas_ia: ['Dissertação de mestrado: obrigatoriamente hipóteses testáveis', 'H0 e H1 devem ser claras', 'Variáveis dependentes e independentes identificadas'], elementos_obrigatorios: ['pergunta de pesquisa', 'H0', 'H1', 'variáveis'], erros_comuns: ['Hipóteses não testáveis', 'Confundir hipótese com objetivo'], min_palavras: 200, max_palavras: 500 },
      { id: 'objetivos', chave_secao: 'objetivos', nome: 'Objetivos', descricao: 'Geral e específicos mensuráveis', obrigatoria: true, tempo_estimado_minutos: 15, instrucoes: 'Objetivo geral alinhado à pergunta. Objetivos específicos (4-6) que formam os capítulos da dissertação.', dicas_ia: ['Cada objetivo específico pode virar um artigo ou capítulo', 'Use verbos mensuráveis: identificar, comparar, analisar, avaliar'], elementos_obrigatorios: ['objetivo geral', 'objetivos específicos'], erros_comuns: ['Objetivos genéricos', 'Sem alinhamento com hipóteses'], min_palavras: 150, max_palavras: 400 },
      { id: 'justificativa', chave_secao: 'justificativa', nome: 'Justificativa', descricao: 'Relevância científica e social', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Justifique a relevância para a área de conhecimento, para a sociedade e para a CAPES/programa de pós-graduação.', dicas_ia: ['Mencione a inserção na linha de pesquisa do programa', 'Dados epidemiológicos e econômicos fortalecem a justificativa', 'Para saúde: carga da doença, morbimortalidade'], elementos_obrigatorios: ['relevância científica', 'relevância social', 'alinhamento com programa'], erros_comuns: ['Justificativa sem dados', 'Não alinhada ao programa de pós'], min_palavras: 400, max_palavras: 800 },
      { id: 'revisao_literatura', chave_secao: 'revisao_literatura', nome: 'Revisão de Literatura', descricao: 'Estado da arte aprofundado', obrigatoria: true, tempo_estimado_minutos: 90, instrucoes: 'Revisão crítica e abrangente da literatura. Organize por subtemas. Identifique consensos, controvérsias e lacunas.', dicas_ia: ['Mestrado: espera-se revisão mais profunda que TCC', 'Inclua artigos clássicos E publicações recentes', 'Finalize cada subtema apontando a lacuna'], elementos_obrigatorios: ['contexto do tema', 'revisão por subtemas', 'consensos e controvérsias', 'lacunas identificadas'], erros_comuns: ['Superficial', 'Sem síntese crítica', 'Apenas resumir artigos'], min_palavras: 3000, max_palavras: 8000 },
      { id: 'referencial_teorico', chave_secao: 'referencial_teorico', nome: 'Referencial Teórico', descricao: 'Arcabouço teórico da dissertação', obrigatoria: true, tempo_estimado_minutos: 40, instrucoes: 'Apresente as teorias, modelos e frameworks que fundamentam e guiam a pesquisa.', dicas_ia: ['Diferencie de revisão de literatura: aqui são os conceitos estruturantes', 'Mostre como cada teoria se aplica ao seu objeto de estudo', 'Cite os autores fundadores das teorias usadas'], elementos_obrigatorios: ['teorias base', 'conceitos-chave', 'aplicação ao objeto de estudo'], erros_comuns: ['Confundir com revisão', 'Teorias sem relação com o trabalho'], min_palavras: 1000, max_palavras: 3000 },
      { id: 'metodologia', chave_secao: 'metodologia', nome: 'Metodologia', descricao: 'Delineamento detalhado da pesquisa', obrigatoria: true, tempo_estimado_minutos: 45, instrucoes: 'Descreva o delineamento, local, população, amostra (com cálculo), instrumentos, coleta e análise em detalhes reprodutíveis.', dicas_ia: ['Nível de detalhe: outro pesquisador deve replicar exatamente', 'Inclua: aprovação do CEP se aplicável', 'Cálculo amostral com justificativa do tamanho de efeito esperado'], elementos_obrigatorios: ['delineamento', 'local e período', 'população e amostra', 'cálculo amostral', 'instrumentos', 'coleta', 'análise'], erros_comuns: ['Metodologia superficial', 'Sem cálculo amostral', 'Análise estatística não descrita'], min_palavras: 1000, max_palavras: 3000 },
      { id: 'aspectos_eticos', chave_secao: 'aspectos_eticos', nome: 'Aspectos Éticos', descricao: 'Conformidade ética da pesquisa', obrigatoria: false, tempo_estimado_minutos: 15, instrucoes: 'Declare aprovação do CEP (número CAAE), procedimentos éticos com participantes e declarações obrigatórias.', dicas_ia: ['Obrigatório para pesquisas com seres humanos', 'Mencione o TCLE e o processo de consentimento', 'Inclua o número CAAE após aprovação'], elementos_obrigatorios: ['aprovação ética', 'TCLE', 'procedimentos de proteção dos participantes'], erros_comuns: ['Omitir CEP em pesquisa com humanos', 'TCLE não mencionado'], min_palavras: 200, max_palavras: 500 },
      { id: 'resultados', chave_secao: 'resultados', nome: 'Resultados', descricao: 'Dados obtidos sem interpretação', obrigatoria: true, tempo_estimado_minutos: 45, instrucoes: 'Apresente os resultados de forma objetiva, com tabelas e figuras, seguindo a ordem dos objetivos.', dicas_ia: ['Resultados ≠ Discussão', 'Organize por objetivo específico', 'Tabela 1: sempre caracterização da amostra'], elementos_obrigatorios: ['caracterização', 'resultados por objetivo', 'dados estatísticos'], erros_comuns: ['Interpretar nos resultados', 'Não descrever tabelas e figuras'], min_palavras: 1000, max_palavras: 4000 },
      { id: 'discussao', chave_secao: 'discussao', nome: 'Discussão', descricao: 'Interpretação e contextualização na literatura', obrigatoria: true, tempo_estimado_minutos: 45, instrucoes: 'Interprete os resultados, compare com a literatura, explique concordâncias/divergências, declare limitações.', dicas_ia: ['1º parágrafo: achado principal', 'Compare cada resultado com estudos da revisão', 'Limitações no penúltimo parágrafo', 'Contribuições no último'], elementos_obrigatorios: ['interpretação', 'comparação com literatura', 'limitações', 'contribuições'], erros_comuns: ['Repetir resultados', 'Sem limitações', 'Discussão muito especulativa'], min_palavras: 1500, max_palavras: 5000 },
      { id: 'conclusao', chave_secao: 'conclusao', nome: 'Conclusão', descricao: 'Síntese final e contribuições do mestrado', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Responda à pergunta de pesquisa, retome os objetivos específicos e destaque as contribuições do trabalho para a área.', dicas_ia: ['Responda à hipótese: confirmada ou refutada?', 'Cada objetivo deve ser retomado brevemente', 'Aponte claramente as contribuições científicas'], elementos_obrigatorios: ['resposta à hipótese', 'alcance dos objetivos', 'contribuições', 'recomendações'], erros_comuns: ['Conclusão igual ao resumo', 'Sem mencionar contribuições', 'Dados novos na conclusão'], min_palavras: 400, max_palavras: 1000 },
      { id: 'limitacoes', chave_secao: 'limitacoes', nome: 'Limitações e Perspectivas', descricao: 'Limitações do estudo e direções futuras', obrigatoria: false, tempo_estimado_minutos: 15, instrucoes: 'Liste as limitações metodológicas e aponte perspectivas para pesquisas futuras.', dicas_ia: ['Limitações metodológicas, não apenas de recursos', 'Perspectivas devem ser concretas e advir das lacunas do estudo', 'Seja honesto — avaliadores valorizam autocrítica'], elementos_obrigatorios: ['limitações metodológicas', 'perspectivas futuras'], erros_comuns: ['Sem limitações', 'Perspectivas muito vagas'], min_palavras: 150, max_palavras: 400 },
      { id: 'resumo', chave_secao: 'resumo', nome: 'Resumo e Abstract', descricao: 'Síntese estruturada em português e inglês', obrigatoria: true, tempo_estimado_minutos: 20, instrucoes: 'Resumo seguindo ABNT NBR 6028: 150-500 palavras. Abstract em inglês. Palavras-chave em ambos os idiomas.', dicas_ia: ['Estrutura: contexto → objetivo → método → resultado → conclusão', 'Dissertação: até 500 palavras (ABNT)', 'Abstract em inglês acadêmico fluente'], elementos_obrigatorios: ['contexto', 'objetivo', 'método', 'resultado', 'conclusão', 'palavras-chave/keywords'], erros_comuns: ['Ultrapassar 500 palavras', 'Abstract como tradução literal'], min_palavras: 150, max_palavras: 500 },
    ],
  },
}

export function getFluxo(tipoTrabalho: string): ConfiguracaoFluxo | null {
  return FLUXOS[tipoTrabalho] ?? null
}

export function getFase(tipoTrabalho: string, chaveSecao: string) {
  return FLUXOS[tipoTrabalho]?.fases.find(f => f.chave_secao === chaveSecao) ?? null
}
