import type { TipoDocumento, DadosProjeto, Referencia, FormatoCitacao } from '@/types'
import { formatarRefsParaPrompt, buildInstrucaoCitacaoReferencias } from '@/lib/ai/prompts'
import { getNormasSecao } from '@/lib/ai/normas-cientificas'

const SYSTEM_PROMPT = `Você é um especialista em pesquisa científica brasileira com profundo domínio em normas ABNT, regulamentações do CEP/CONEP e publicação científica. Gere documentos acadêmicos completos e prontos para uso.

REGRA CRÍTICA — HUMANIZAÇÃO DO TEXTO:
Detectores de IA (GPTZero, Turnitin, Originality.ai) identificam dois padrões específicos no texto:

BURSTINESS — variação de comprimento de frases:
Textos de IA têm frases de comprimento uniforme (15-20 palavras cada). Textos humanos alternam abruptamente.
REGRA OBRIGATÓRIA: a cada 2-3 frases longas (mais de 20 palavras), escreva 1 frase curta com menos de 8 palavras. Exemplo de ritmo correto: "A análise de dados em ensaios clínicos randomizados exige atenção redobrada à aleatorização e ao cegamento dos avaliadores para minimizar vieses sistemáticos. Isso parece óbvio. Mas a maioria dos pesquisadores de primeira viagem subestima o impacto dos dados ausentes sobre o poder estatístico da análise principal."

PERPLEXIDADE — imprevisibilidade lexical:
IA escolhe sempre a palavra mais provável. Humanos surpreendem com dados contraintuitivos, ressalvas inesperadas, analogias incomuns, ou perguntas retóricas.
REGRA OBRIGATÓRIA: cada seção deve ter pelo menos 1 elemento que quebre a expectativa do leitor.

EXPRESSÕES COMPLETAMENTE PROIBIDAS (delação imediata de IA):
"É importante ressaltar", "Cabe destacar", "Nesse contexto", "Diante do exposto",
"De tal forma que", "Tendo em vista", "No que tange", "Com relação a",
"Outrossim", "Destarte", "Assim sendo", "Vale salientar", "É possível observar",
"Conclui-se que", "Em suma", "Sendo assim", "Ante o exposto",
"Salienta-se que", "Evidencia-se que", "Conforme supracitado", "Mormente".

VARIAÇÃO ESTRUTURAL OBRIGATÓRIA:
• Misture parágrafos de prosa corrida com listas e tabelas — não escreva tudo em bullets
• Inclua pelo menos uma "Nota prática:" ou "Atenção:" com dica concreta
• Varie o comprimento dos parágrafos: alguns com 5 linhas, outros com 1
• Inclua ressalvas reais ("embora seja tentador...", "a exceção ocorre quando...", "isso só funciona se...")
• Em documentos técnicos: alterne seções de código/fórmulas com explicação em prosa conversacional
• Use exemplos com valores numéricos concretos e outputs reais de software

PROIBIDO ABSOLUTAMENTE — nunca inclua no documento gerado:
• Qualquer linha de metadado como "Gerado em [data]", "Gerado por Científica AI", "AI-assisted", "Generated by"
• Cabeçalhos de autoria do aplicativo
• Referência ao nome de qualquer ferramenta de IA
Comece o documento direto com o conteúdo solicitado.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚫 DADOS DE IDENTIFICAÇÃO — NUNCA INVENTAR (regra inviolável)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
É TERMINANTEMENTE PROIBIDO inventar qualquer dado administrativo, pessoal ou institucional que NÃO tenha sido explicitamente fornecido nos dados do projeto. Isso inclui:
✗ Nome do pesquisador, orientador, coautores (ex: "Dr. Carlos Alberto Mendes")
✗ Números de registro profissional (CRM, COREN, CRP, etc.) — ex: "CRM 12345-SP"
✗ Nome de instituições, hospitais, universidades, maternidades (ex: "HCFMUSP", "Maternidade do Jabaquara")
✗ Fontes de financiamento, valores, agências de fomento, números de processo
✗ Números CAAE, parecer do CEP, datas de aprovação, número de registro ReBEC/ClinicalTrials
✗ Endereços, telefones, e-mails, CNPJ

Para CADA um desses dados que não foi fornecido, use EXATAMENTE um marcador entre colchetes que o pesquisador preencherá:
[NOME DO PESQUISADOR RESPONSÁVEL]  [Nº DO CRM/REGISTRO]  [INSTITUIÇÃO PROPONENTE]
[INSTITUIÇÃO COPARTICIPANTE]  [FONTE DE FINANCIAMENTO]  [Nº CAAE]  [Nº DO PARECER CEP]

Use os dados REAIS do projeto APENAS quando estiverem explicitamente fornecidos nos "DADOS DO PROJETO" acima (ex: local e período previstos). Para todo o resto: COLCHETES. Inventar um nome de médico com CRM falso é fraude documental — JAMAIS faça isso.`

function buildRevisaoLiteratura(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere uma Revisão de Literatura completa e estruturada para fundamentar a pesquisa descrita acima.

Título provisório: ${titulo ?? dados.titulo_provisorio}
Pergunta de pesquisa: ${dados.pergunta_pesquisa}
Delineamento: ${dados.delineamento}

A revisão deve conter:

1. CONTEXTO E MAGNITUDE DO PROBLEMA
   Apresente dados epidemiológicos, estatísticas nacionais e internacionais relevantes ao tema.
   Use linguagem acadêmica mas acessível. Cite tipos de fontes que o pesquisador deve buscar
   (ex: "Segundo dados do Ministério da Saúde...", "Estudos internacionais demonstram...").
   Mínimo 300 palavras.

2. ESTADO ATUAL DO CONHECIMENTO
   2.1 O que já se sabe sobre o tema (principais achados da literatura)
   2.2 O que ainda não está claro ou é controverso
   2.3 Lacuna que esta pesquisa vai preencher

3. REFERENCIAL TEÓRICO
   Apresente os principais conceitos, teorias e modelos relevantes para o tema.
   Explique cada conceito de forma didática.

4. INSTRUMENTOS E MÉTODOS JÁ UTILIZADOS NA LITERATURA
   Liste os instrumentos validados (escalas, questionários, métodos) que foram usados
   em pesquisas similares. Para cada um: nome, o que mede, vantagens e limitações.
   Mencione especificamente: ${dados.instrumentos_previstos}

5. EVIDÊNCIAS NACIONAIS (BRASIL)
   Destaque o que a literatura brasileira já produziu sobre o tema.
   Se houver lacuna nacional, aponte como justificativa para este estudo.

6. JUSTIFICATIVA DESTA PESQUISA
   Parágrafo síntese de por que este estudo é relevante, original e necessário,
   conectando a lacuna identificada com o objetivo desta pesquisa.

7. REFERÊNCIAS
   Liste, ao final, as referências REAIS que você efetivamente citou ao longo do texto,
   no formato de citação escolhido. Use APENAS as referências reais fornecidas na lista
   de "REFERÊNCIAS REAIS DISPONÍVEIS" (se houver) — nunca invente.

IMPORTANTE: Escreva em português brasileiro com linguagem acadêmica, mas com ritmo variado — alterne parágrafos densos com parágrafos curtos de 1-2 frases. Inclua pelo menos uma ressalva ou dado contraintuitivo por seção. CADA afirmação factual (epidemiologia, estatística, achado de estudo, diretriz) DEVE ter uma citação real imediatamente após. JAMAIS escreva "(verificar referência)", "(referência)", "(citar fonte)" ou marcadores similares — use uma referência real da lista fornecida. Evite estrutura roboticamente uniforme: parágrafos de tamanhos diferentes, sem usar as mesmas expressões de transição mais de uma vez.`
}

function dadosResumo(dados: DadosProjeto): string {
  return `
DADOS DO PROJETO:
- Título provisório: ${dados.titulo_provisorio}
- Pergunta de pesquisa: ${dados.pergunta_pesquisa}
- Objetivo geral: ${dados.objetivo_geral}
- Delineamento: ${dados.delineamento}
- População-alvo: ${dados.populacao_alvo}
- Amostra estimada: ${dados.amostra_estimada}
- Local previsto: ${dados.local_previsto}
- Período previsto: ${dados.periodo_previsto}
- Instrumentos previstos: ${dados.instrumentos_previstos}
- Análise prevista: ${dados.analise_prevista}
- Justificativa: ${dados.justificativa_resumida}
- Contexto geral: ${dados.contexto_geral}
`.trim()
}

function buildProtocoloCep(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere um Protocolo de Pesquisa completo para submissão ao Comitê de Ética em Pesquisa (CEP) via Plataforma Brasil, seguindo rigorosamente a Resolução CNS 466/2012 e a Norma Operacional CNS 001/2013.

O protocolo deve conter as seguintes seções obrigatórias, com conteúdo completo e adequado ao projeto descrito acima:

1. IDENTIFICAÇÃO DO PROJETO (copie EXATAMENTE os marcadores entre colchetes — NÃO invente nomes, instituições, CRM ou financiamento)
   - Título completo: ${titulo ?? dados.titulo_provisorio ?? '[TÍTULO DO PROJETO]'}
   - Pesquisador responsável: [NOME DO PESQUISADOR RESPONSÁVEL]
   - Registro profissional: [Nº DO CRM/COREN/REGISTRO]
   - Instituição proponente: [INSTITUIÇÃO PROPONENTE]
   - Instituição co-participante (se houver): [INSTITUIÇÃO COPARTICIPANTE OU "Não se aplica"]
   - Local de realização: ${dados.local_previsto?.trim() ? dados.local_previsto : '[LOCAL DE REALIZAÇÃO]'}
   - Período de execução: ${dados.periodo_previsto?.trim() ? dados.periodo_previsto : '[PERÍODO DE EXECUÇÃO]'}
   - Financiamento: [FONTE DE FINANCIAMENTO OU "Recursos próprios dos pesquisadores"]
   ATENÇÃO: mantenha os marcadores [ENTRE COLCHETES] exatamente como estão para os campos não preenchidos. NUNCA substitua por nomes ou instituições inventados.

2. INTRODUÇÃO E JUSTIFICATIVA
   Redija com base no contexto e justificativa do projeto (mínimo 400 palavras).

3. OBJETIVOS
   3.1 Objetivo Geral
   3.2 Objetivos Específicos (liste pelo menos 3)

4. METODOLOGIA
   4.1 Tipo de estudo e delineamento
   4.2 Local e período
   4.3 População e critérios de inclusão/exclusão
   4.4 Amostragem (cálculo amostral e justificativa)
   4.5 Instrumentos e técnicas de coleta de dados
   4.6 Procedimentos de coleta
   4.7 Análise de dados

5. ASPECTOS ÉTICOS
   5.1 Riscos e desconfortos previstos e medidas de minimização
   5.2 Benefícios diretos e indiretos
   5.3 Formas de garantia de sigilo e confidencialidade
   5.4 Procedimento de obtenção do TCLE
   5.5 Armazenamento e destino dos dados após a pesquisa
   5.6 Critérios para suspensão ou encerramento da pesquisa

6. CRONOGRAMA
   Tabela com fases, atividades e meses (${dados.periodo_previsto})

7. ORÇAMENTO DETALHADO
   Tabela de recursos humanos, materiais, deslocamentos e outros

8. REFERÊNCIAS BIBLIOGRÁFICAS
   Liste APENAS as referências reais que você efetivamente citou ao longo do texto.
   FORMATO DA LISTA (siga rigorosamente o estilo de citação do trabalho):
   • ABNT → ordem ALFABÉTICA pelo sobrenome do 1º autor, SEM numeração. Cada entrada: SOBRENOME, Nome. Título. Periódico, volume, número, páginas, ano.
   • Vancouver → NUMERADA na ordem em que as referências aparecem no texto (1, 2, 3...).
   • APA → ordem ALFABÉTICA pelo sobrenome, SEM numeração.
   NUNCA misture estilos (ex: lista numerada com entradas ABNT). A lista e as citações no texto devem usar o MESMO estilo.
   REGRA: toda referência listada aqui DEVE ter sido citada no texto; e toda citação do texto DEVE constar nesta lista.

CITAÇÕES NO CORPO DO TEXTO: cite as referências reais ao longo das seções 2 (Introdução/Justificativa), 4 (Metodologia — instrumentos, escalas, cálculo amostral) e 5 (Aspectos Éticos — Resolução 466/2012). Cada afirmação factual deve ter citação. NÃO deixe a lista de referências órfã (referências listadas mas não citadas no texto).

Produza o documento completo, formal, em português brasileiro, pronto para ser copiado e inserido na Plataforma Brasil.

ESTILO NAS SEÇÕES NARRATIVAS (Introdução, Justificativa, Aspectos Éticos): Alterne parágrafos longos com frases curtas de impacto. Inclua pelo menos uma ressalva real por seção ("embora...", "a exceção ocorre..."). PROIBIDO: "É importante ressaltar", "Nesse contexto", "Diante do exposto", "Outrossim", "Destarte", "Sendo assim", "Cabe destacar".`
}

function buildCartaAnuencia(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere uma Carta de Anuência Institucional completa e formal para que [NOME DO PESQUISADOR], [CARGO/FUNÇÃO] da [INSTITUIÇÃO DO PESQUISADOR], solicite autorização para realizar a pesquisa intitulada "${titulo ?? dados.titulo_provisorio}" nas dependências de [NOME DA INSTITUIÇÃO COPARTICIPANTE].

A carta deve:
- Ser endereçada ao Ilmo. Sr./Sra. [NOME DO DIRETOR/RESPONSÁVEL], [CARGO], da [NOME DA INSTITUIÇÃO]
- Apresentar o pesquisador e sua vinculação institucional
- Descrever claramente o objetivo da pesquisa (use o objetivo geral do projeto)
- Explicar os procedimentos que serão realizados na instituição: ${dados.instrumentos_previstos}
- Informar o período de coleta de dados: ${dados.periodo_previsto}
- Mencionar a população envolvida: ${dados.populacao_alvo}
- Destacar que a pesquisa está em processo de aprovação pelo CEP
- Afirmar compromisso com a Resolução CNS 466/2012 e sigilo dos dados
- Informar que haverá devolução dos resultados à instituição
- Incluir campo para assinatura do responsável institucional autorizando a pesquisa
- Usar linguagem formal e respeitosa
- Incluir local, data e campos de assinatura do pesquisador e do representante institucional

Formate como carta oficial brasileira (com cabeçalho, corpo, fechamento e campos de assinatura).

ESTILO: Escreva de forma direta e profissional. Varie levemente o comprimento das frases. Evite linguagem roboticamente formal: prefira "solicita autorização" a "vem mui respeitosamente requerer". Inclua 1-2 frases com ritmo curto para destacar compromissos.`
}

function buildTcle(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere um Termo de Consentimento Livre e Esclarecido (TCLE) completo, seguindo as diretrizes da Resolução CNS 466/2012 e orientações do CONEP, para a pesquisa intitulada "${titulo ?? dados.titulo_provisorio}".

O TCLE deve conter obrigatoriamente:

1. CABEÇALHO
   - Título da pesquisa
   - Nome do pesquisador responsável: [NOME DO PESQUISADOR]
   - Instituição: [NOME DA INSTITUIÇÃO]
   - Contatos: [TELEFONE] | [E-MAIL]

2. CONVITE
   Texto de convite claro e acessível (linguagem simples, nível médio de escolaridade), explicando que a participação é voluntária.

3. OBJETIVOS DA PESQUISA
   Explique o objetivo geral em linguagem acessível (sem jargão técnico).

4. PROCEDIMENTOS
   Descreva em detalhes o que será pedido ao participante:
   - Quais instrumentos serão aplicados: ${dados.instrumentos_previstos}
   - Tempo estimado de participação
   - Local e forma de realização

5. RISCOS
   Liste os riscos e desconfortos previstos (cansaço, constrangimento, etc.) e as medidas de minimização.

6. BENEFÍCIOS
   Benefícios diretos ao participante e à sociedade.

7. VOLUNTARIEDADE E DIREITO DE RECUSA
   Esclareça que a participação é voluntária e que o participante pode retirar o consentimento a qualquer momento sem prejuízo.

8. CONFIDENCIALIDADE E PRIVACIDADE
   Garantia de sigilo, anonimização dos dados, quem terá acesso, prazo de guarda dos dados (mínimo 5 anos conforme Res. CNS 466/2012).

9. RESSARCIMENTO E INDENIZAÇÃO
   Se houver algum custo, será ressarcido; em caso de dano, haverá indenização conforme previsto em lei.

10. CONTATO DO PESQUISADOR E DO CEP
    - Pesquisador: [NOME], [TELEFONE], [E-MAIL]
    - CEP da Instituição: [NOME DO CEP], [TELEFONE], [E-MAIL], [ENDEREÇO]
    - CONEP (para casos de conflito): [telefone CONEP]

11. DECLARAÇÃO DE CONSENTIMENTO
    "Eu, _______________________, RG nº ______________, declaro ter sido informado(a) e concordo em participar, como voluntário(a), da pesquisa acima descrita."
    - Campos: nome completo, RG, data, assinatura do participante
    - Assinatura do pesquisador responsável
    - Caso o participante não saiba assinar: testemunha

12. DUAS VIAS
    Nota informando que o TCLE é emitido em duas vias, uma para o participante e outra para o pesquisador.

Use linguagem clara, direta e empática. O documento deve ser completo e pronto para uso.

ESTILO OBRIGATÓRIO: Nas seções descritivas (Objetivos, Procedimentos, Riscos, Benefícios), use linguagem simples e variada — misture frases curtas de 1 linha com explicações mais longas. Nunca use "É importante ressaltar", "Diante do exposto", "Nesse contexto", "Destarte". O participante precisa entender facilmente.`
}

function buildInstrumentoColeta(dados: DadosProjeto): string {
  return `${dadosResumo(dados)}

Gere um instrumento de coleta de dados completo e validado para a pesquisa descrita acima.

Instrumento: ${dados.instrumentos_previstos}
Delineamento: ${dados.delineamento}
População-alvo: ${dados.populacao_alvo}
Análise prevista: ${dados.analise_prevista}

O instrumento deve conter:

1. CABEÇALHO DO INSTRUMENTO
   - Título da pesquisa
   - Número de identificação do participante (ID, sem nome)
   - Data de coleta
   - Nome do entrevistador/aplicador (se aplicável)

2. SEÇÃO A — DADOS SOCIODEMOGRÁFICOS
   Variáveis relevantes para a população-alvo: idade, sexo, escolaridade, tempo de atuação (se profissional), e outras pertinentes.
   Para cada variável: opções de resposta claras e código numérico para análise.

3. SEÇÃO B — VARIÁVEIS PRINCIPAIS
   Crie questões específicas relacionadas à pergunta de pesquisa: "${dados.pergunta_pesquisa}"
   - Se escalas validadas forem aplicáveis (ex: Likert 1-5, escala visual analógica), utilize-as
   - Inclua instruções de preenchimento para cada seção
   - Numere todas as questões sequencialmente

4. SEÇÃO C — DESFECHOS SECUNDÁRIOS (se aplicável)
   Variáveis secundárias relevantes ao objetivo da pesquisa.

5. ESPAÇO PARA OBSERVAÇÕES DO PESQUISADOR

6. INSTRUÇÕES DE PREENCHIMENTO
   Instruções claras ao entrevistador/aplicador sobre como preencher corretamente cada seção.

7. CÓDIGO DE ANÁLISE
   Tabela de codificação de variáveis para análise no software ${dados.analise_prevista}.

Produza o instrumento completo, numerado e pronto para aplicação.

ESTILO NAS INSTRUÇÕES E DESCRIÇÕES: Use linguagem direta e prática. Alterne entre frases curtas (instruções) e explicações mais longas. Evite o estilo "lista de IA" onde cada item é idêntico em estrutura e comprimento.`
}

function buildCalculoAmostral(dados: DadosProjeto): string {
  return `${dadosResumo(dados)}

Gere um Cálculo Amostral completo, detalhado e justificado para a pesquisa descrita acima.

O documento deve conter:

1. CONTEXTO E JUSTIFICATIVA DO CÁLCULO
   Explique por que o cálculo amostral é necessário: garantir poder estatístico suficiente para detectar diferenças reais, evitar sub ou superdimensionamento da amostra, e atender à exigência do CEP.

2. PARÂMETROS UTILIZADOS
   Defina e justifique cada parâmetro com base no tipo de estudo (${dados.delineamento}):
   - Nível de significância (α): geralmente 0,05 → erro tipo I de 5%
   - Poder estatístico (1-β): geralmente 0,80 (80%) ou 0,90 (90%) → justifique
   - Tamanho de efeito esperado: pequeno (d=0,2), médio (d=0,5) ou grande (d=0,8) — baseado na literatura para este tema
   - Proporções esperadas ou diferença mínima detectável (conforme o delineamento)
   - Perdas e recusas esperadas: acréscimo de 10-20% ao N calculado

3. FÓRMULA UTILIZADA
   Apresente a fórmula estatística adequada ao delineamento:
   - Para comparação de dois grupos independentes: fórmula para teste t independente
   - Para estudo transversal/prevalência: fórmula de proporção populacional
   - Para correlação: fórmula baseada no r esperado
   - Para outros delineamentos: adapte conforme necessário
   Mostre a fórmula em notação matemática clara.

4. CÁLCULO PASSO A PASSO
   Substitua os valores na fórmula e mostre o cálculo passo a passo.
   Resultado: N mínimo por grupo (se aplicável) e N total.
   Adicione a margem de perdas/recusas: N final recomendado.

5. VERIFICAÇÃO POR SOFTWARE
   Forneça o código para calcular e verificar o N nos seguintes softwares:

   **R (pacote pwr):**
   \`\`\`r
   # Instale se necessário: install.packages("pwr")
   library(pwr)
   # [código específico para este delineamento]
   \`\`\`

   **G*Power (software gratuito):**
   Passo a passo para verificar no G*Power 3.1:
   - Test family: [família de testes]
   - Statistical test: [teste específico]
   - Type of power analysis: [tipo]
   - Input parameters: [valores]

   **Python (scipy/statsmodels):**
   \`\`\`python
   # [código equivalente]
   \`\`\`

6. RESULTADO FINAL E RECOMENDAÇÃO
   **N mínimo calculado:** [valor]
   **Acréscimo para perdas (X%):** [valor]
   **N total recomendado para coleta:** [valor]

   Compare com a amostra estimada no plano (${dados.amostra_estimada}) e comente se é adequada, subdimensionada ou superdimensionada.

7. TEXTO PRONTO PARA A SEÇÃO DE MÉTODOS
   Forneça um parágrafo completo e formatado para inserir na seção "Casuística e Métodos" do manuscrito, descrevendo o cálculo amostral em linguagem científica.

8. REFERÊNCIAS DO CÁLCULO
   Cite as referências metodológicas utilizadas (Cohen, 1988; ou outra referência padrão para o método), em formato ABNT.

Produza o documento completo, com todos os cálculos realizados e o texto pronto para uso no manuscrito e no protocolo CEP.

ESTILO NAS SEÇÕES NARRATIVAS (Contexto, Justificativa, Resultado Final, Texto para Métodos): Alterne parágrafos densos com frases curtas de conclusão ("O N final recomendado é X."). Inclua pelo menos uma ressalva sobre limitações do cálculo. PROIBIDO: "É importante ressaltar", "Nesse contexto", "Diante do exposto", "Destarte", "Sendo assim".`
}

function buildGuiaColeta(dados: DadosProjeto): string {
  return `${dadosResumo(dados)}

Gere um Guia Operacional de Coleta de Dados detalhado e passo a passo para o projeto de pesquisa descrito acima.

O guia deve ser prático, claro e seguir a seguinte estrutura:

1. INTRODUÇÃO E OBJETIVO DO GUIA
   Explique a finalidade deste guia e quem deve usá-lo.

2. PRÉ-REQUISITOS ANTES DE IR A CAMPO
   Lista de verificação (checklist) com tudo o que o pesquisador deve providenciar antes da coleta:
   - Aprovação do CEP (número do parecer)
   - Materiais impressos necessários (quantos TCLEs, quantos questionários)
   - Equipamentos (gravador, tablet, canetas, etc.)
   - Contatos dos responsáveis na instituição
   - Crachá/identificação do pesquisador

3. PROCEDIMENTO PADRÃO DE ABORDAGEM DO PARTICIPANTE
   Script de abordagem passo a passo:
   - Como se apresentar
   - Como explicar a pesquisa em linguagem leiga
   - Como apresentar e coletar o TCLE
   - Como aplicar o instrumento: ${dados.instrumentos_previstos}
   - Tempo estimado por participante
   - Como proceder em caso de recusa

4. DURANTE A COLETA
   - Onde sentar/posicionar o participante
   - Ambiente adequado (privacidade, silêncio)
   - Como registrar respostas ambíguas
   - Como lidar com perguntas do participante
   - Como proceder se o participante desistir no meio

5. CRITÉRIOS DE INCLUSÃO E EXCLUSÃO NA PRÁTICA
   Como identificar na prática quem incluir: ${dados.populacao_alvo}

6. CONTROLE DE QUALIDADE DOS DADOS
   - Como revisar o questionário antes de o participante ir embora
   - O que fazer com instrumentos incompletos
   - Como numerar e organizar os instrumentos coletados

7. ARMAZENAMENTO E TRANSPORTE DOS DADOS
   - Onde guardar os instrumentos físicos (local seguro, acesso restrito)
   - Como digitalizar os dados (prazo, responsável)
   - Backup dos dados digitais

8. REGISTRO DIÁRIO DE CAMPO
   Modelo de registro diário: data, local, número de abordagens, inclusões, recusas, intercorrências.

9. CRONOGRAMA OPERACIONAL DE COLETA
   Tabela com semanas, locais, metas de participantes e responsáveis.

10. CONTATOS DE EMERGÊNCIA
    - Pesquisador responsável
    - Orientador
    - Responsável na instituição coparticipante

Produza o guia completo, formal e pronto para uso em campo.

ESTILO: Escreva as seções narrativas (Introdução, Scripts de abordagem, Controle de qualidade) com ritmo variado — alterne frases de instrução curtas com explicações em prosa. Inclua pelo menos 1 "Atenção:" ou "Nota de campo:" com dica prática por seção principal. PROIBIDO: "É importante ressaltar", "Nesse contexto", "Destarte", "Outrossim".`
}

function buildProtocoloExtracao(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere um PROTOCOLO DE SELEÇÃO E EXTRAÇÃO DE DADOS para uma revisão de literatura/estudos${titulo ? ` sobre "${titulo}"` : ''}. É um documento de TRABALHO que o pesquisador usa enquanto lê os artigos — não é prosa corrida. Baseie tudo na pergunta e no objetivo abaixo; NÃO invente achados nem números de estudos.

Pergunta de pesquisa: ${dados.pergunta_pesquisa}
Objetivo: ${dados.objetivo_geral}
População/contexto de interesse: ${dados.populacao_alvo || '[definir]'}

O documento DEVE conter, nesta ordem:

1. CRITÉRIOS DE ELEGIBILIDADE
   Derive da pergunta de pesquisa critérios objetivos, em duas listas claras:
   - CRITÉRIOS DE INCLUSÃO (tipo de estudo, população, intervenção/exposição, desfecho, idioma, recorte temporal — proponha valores coerentes com a pergunta, deixando [colchetes] onde o pesquisador deve decidir).
   - CRITÉRIOS DE EXCLUSÃO (o que descartar e por quê).

2. FLUXO DE SELEÇÃO (PRISMA)
   Tabela/registro com as 4 etapas: Identificação (nº de registros por base) → Triagem por título e resumo (excluídos + motivo) → Leitura na íntegra (excluídos + motivo) → Estudos incluídos. Deixe os números em [colchetes] para o pesquisador preencher.

3. FORMULÁRIO DE EXTRAÇÃO DE DADOS (um por artigo incluído)
   Modelo de ficha com os campos, prontos para preencher por estudo:
   - Identificação: autor(es) e ano; país; periódico
   - Delineamento do estudo
   - População e amostra (N, características)
   - Intervenção/Exposição e Comparador (quando houver)
   - Desfechos medidos
   - Principais resultados (com os números do próprio artigo)
   - Limitações apontadas
   - Avaliação de qualidade / risco de viés (proponha o instrumento adequado ao delineamento — ex.: JBI, Newcastle-Ottawa, RoB 2 — e os domínios a marcar)
   - Observações do revisor

4. TABELA-SÍNTESE DAS CARACTERÍSTICAS DOS ESTUDOS
   Cabeçalho de uma tabela (Autor/Ano | Delineamento | População/N | Intervenção | Desfecho | Principais resultados | Qualidade) com 1–2 linhas de EXEMPLO preenchidas com [colchetes] mostrando como usar.

5. COMO USAR ESTE PROTOCOLO
   Passo a passo curto: triar por título/resumo aplicando os critérios; ler na íntegra os que passaram; preencher uma ficha por estudo incluído; registrar os motivos de exclusão; consolidar tudo na tabela-síntese para depois redigir a Discussão.

ESTILO: linguagem direta e prática (é um instrumento de trabalho). Use tabelas e listas onde fizer sentido. NUNCA invente autores, anos, números de estudos ou resultados — esses campos são do pesquisador (use [colchetes]).`
}

function buildGuiaAnalise(dados: DadosProjeto): string {
  const softwareEscolhido = dados.software_analise
    ? `O pesquisador escolheu: **${dados.software_analise}**. Todos os exemplos de código e passo a passo devem ser para esse software.`
    : 'O pesquisador ainda não definiu o software. Recomende o mais adequado e justifique a escolha.'

  return `${dadosResumo(dados)}

Gere um Guia de Análise Estatística para o projeto acima.

Análise prevista: ${dados.analise_prevista}
Delineamento: ${dados.delineamento}
Amostra estimada: ${dados.amostra_estimada}
${dados.n_participantes ? `N real coletado: ${dados.n_participantes}` : ''}
${dados.taxa_resposta ? `Taxa de resposta: ${dados.taxa_resposta}` : ''}
SOFTWARE: ${softwareEscolhido}

FORMATO EXIGIDO — MISTURE PROSA COM ESTRUTURA:
Cada seção deve alternar entre parágrafos de prosa explicativa e listas/código. Não escreva tudo em bullets. Um guia técnico escrito por humano tem ritmo: explica em prosa → mostra o código → comenta o resultado em prosa → avisa sobre armadilhas. Siga esse padrão.

Para cada seção, inclua pelo menos:
- Um parágrafo de prosa curto explicando o raciocínio por trás da decisão analítica
- Um exemplo concreto com valores numéricos plausíveis para este estudo
- Uma "Nota prática:" com uma armadilha real que pesquisadores cometem

SEÇÕES OBRIGATÓRIAS:

1. ESTRATÉGIA ANALÍTICA GERAL
Escreva em PROSA (não em lista) a lógica da abordagem: por que esses testes, o que o delineamento determina, e qual é a sequência de análises. Mencione especificamente a pergunta de pesquisa. Máximo 200 palavras, ritmo variado.

2. SOFTWARE: CONFIGURAÇÃO E CITAÇÃO
${dados.software_analise
  ? `Versão recomendada do ${dados.software_analise}, onde obter (licença institucional, download), e a citação correta para o manuscrito. Inclua o comando de verificação de versão.`
  : 'Recomende o software com justificativa baseada no delineamento. Compare 2 alternativas em prosa (não tabela). Inclua como citar no manuscrito.'
}

3. PREPARAÇÃO DOS DADOS (passo a passo realista)
Escreva como se estivesse explicando a um colega ao telefone. Cubra: importação, missing data (quando excluir vs. imputar — dê a regra dos 5%), outliers (o que fazer quando Shapiro-Wilk falha?), e criação de variáveis derivadas. Inclua código de exemplo.

4. ANÁLISE DESCRITIVA
Mostre como montar a "Tabela 1" para este estudo específico. Inclua o código para gerar a tabela e um exemplo de como ela ficaria preenchida com valores fictícios plausíveis para esta população.

5. VERIFICAÇÃO DE PREMISSAS
Explique em prosa quando usar Shapiro-Wilk versus Kolmogorov-Smirnov e por quê n < 50 muda a decisão. Inclua o código. Diga o que fazer quando a premissa É violada — muitos guias param aqui, mas é exatamente onde o pesquisador fica perdido.

6. TESTES PRINCIPAIS E CÓDIGO
Para cada objetivo do projeto, mostre:
- O teste escolhido e por quê (1 frase de justificativa)
- Código completo e funcional no software escolhido
- Como interpretar o output: exemplo de saída real com p-valor, estatística de teste, tamanho de efeito
- Como reportar no manuscrito (frase modelo pronta)

7. ANÁLISES COMPLEMENTARES
Seja seletivo: mencione apenas as que são relevantes para este delineamento específico. Explique em prosa quando uma análise de sensibilidade é necessária versus quando é opcional.

8. INTERPRETAÇÃO E REDAÇÃO DOS RESULTADOS
Dê frases-modelo prontas para copiar no manuscrito, com os valores entre colchetes para preencher. Inclua o que fazer quando p está entre 0,05 e 0,10 — zona cinzenta que ninguém explica.

9. PODER ESTATÍSTICO
Com base na amostra de ${dados.amostra_estimada}, calcule o poder post-hoc e explique o que fazer se for abaixo de 0,80.

10. CHECKLIST PRÉ-SUBMISSÃO
Lista enxuta (máximo 12 itens) do que verificar. Não repita tudo que foi dito antes — foque no que os revisores de periódicos mais rejeitam.

Escreva de forma direta e útil. Inclua humor técnico leve quando adequado ("Se o Shapiro-Wilk der p < 0,001 com n = 200, provavelmente é outlier mesmo — não o teste mentindo"). Varie o comprimento das frases: curtas e longas alternadas.`
}

function buildSugestoesPeriodicos(dados: DadosProjeto): string {
  return `${dadosResumo(dados)}

Com base nos dados do projeto de pesquisa acima, sugira de 6 a 8 periódicos científicos adequados para submissão do manuscrito resultante.

Inclua uma mix equilibrado de:
- Periódicos brasileiros indexados (SciELO, LILACS) com ISSN
- Periódicos internacionais com alto fator de impacto (Web of Science, Scopus)

Para cada periódico, forneça obrigatoriamente:

**[NOME DO PERIÓDICO]**
- ISSN: XXXX-XXXX (impresso) / XXXX-XXXX (eletrônico)
- Editora/Sociedade:
- Fator de Impacto (JCR/CiteScore): [valor e ano]
- Qualis CAPES (área mais relevante):
- Escopo e foco: (2-3 frases sobre o que o periódico publica)
- Tipos de artigo aceitos: original, revisão, relato de caso, etc.
- Idioma de submissão: Português / Inglês / Ambos
- Tempo médio de revisão:
- Taxa de aceitação aproximada:
- Custo de publicação (APC): gratuito / R$XX ou US$XX (se for open access pago)
- URL para submissão: https://...
- Por que é adequado para esta pesquisa: (1-2 frases específicas)

Ordene do mais ao menos recomendado. Ao final, acrescente uma seção "DICAS PARA ESCOLHA DO PERIÓDICO" com 3-4 orientações práticas baseadas neste projeto específico.

ESTILO NA SEÇÃO DE DICAS E NAS JUSTIFICATIVAS: Escreva em prosa com ritmo variado. Misture frases curtas com análises mais longas. Inclua pelo menos 1 dado surpreendente ou ressalva inesperada (ex: "Curiosamente, o periódico X aceita artigos em português mas raramente publica estudos brasileiros"). PROIBIDO: "É importante ressaltar", "Nesse contexto", "Destarte".`
}

function buildCartaSubmissao(dados: DadosProjeto, titulo?: string): string {
  return `${dadosResumo(dados)}

Gere uma Carta de Apresentação (Cover Letter) completa em inglês e português para submissão do manuscrito resultante desta pesquisa a um periódico científico.

Título do manuscrito: ${titulo ?? dados.titulo_provisorio}

A carta deve:

**VERSÃO EM INGLÊS (Cover Letter)**

Dear Editor-in-Chief,

[Parágrafo 1 — Apresentação do manuscrito]
- Título do trabalho
- Tipo de artigo (original research, review, case report, etc.)
- Nome do periódico para o qual está sendo submetido
- Declaração de que o artigo é original e inédito

[Parágrafo 2 — Contexto e relevância]
- Por que este tema é importante (2-3 frases baseadas na justificativa do projeto)
- Gap de conhecimento que o estudo preenche
- Principal achado ou contribuição (sem revelar resultados ainda)

[Parágrafo 3 — Adequação ao periódico]
- Por que o estudo se alinha ao escopo e ao público-alvo deste periódico
- Potencial de impacto para os leitores

[Parágrafo 4 — Declarações obrigatórias]
- Todos os autores aprovaram a versão final
- Não há conflito de interesses (ou declarar se houver)
- O estudo foi aprovado pelo Comitê de Ética (mencionar número do parecer: [NÚMERO DO PARECER CEP])
- TCLE obtido de todos os participantes (se aplicável)
- Não está sendo avaliado simultaneamente em outro periódico

[Fechamento]
Assinatura do autor correspondente: [NOME DO AUTOR CORRESPONDENTE]
Afiliação: [INSTITUIÇÃO]
E-mail: [E-MAIL]
Telefone: [TELEFONE]
ORCID: [ORCID]

---

**VERSÃO EM PORTUGUÊS (tradução)**

[Mesma estrutura, traduzida adequadamente]

Produza ambas as versões completas e prontas para uso.

ESTILO: Escreva de forma profissional mas não roboticamente uniforme. Cada parágrafo deve ter comprimento diferente. A versão em inglês deve soar como escrita por nativo (use construções naturais, não tradução literal). Inclua 1-2 frases curtas de impacto. PROIBIDO em português: "É importante ressaltar", "Nesse contexto", "Destarte", "Sendo assim".`
}

function buildChecklistSubmissao(dados: DadosProjeto): string {
  return `${dadosResumo(dados)}

Gere um Checklist Completo de Pré-Submissão para periódico científico, adequado ao tipo de estudo descrito acima (${dados.delineamento}).

O checklist deve estar organizado por categorias, com cada item em formato de caixa de seleção ([ ]) e uma explicação breve. Inclua a justificativa de cada item para que o pesquisador entenda por que é importante.

**CATEGORIA 1 — MANUSCRITO PRINCIPAL**
[ ] Título: conciso, descritivo, sem abreviações, ≤ 15 palavras
[ ] Título corrido (running title): ≤ 50 caracteres
[ ] Autores: todos os nomes completos, afiliações numeradas, autor correspondente identificado
[ ] Contribuição dos autores (CRediT taxonomy): Conceptualization, Methodology, Writing, etc.
[ ] Resumo estruturado: Objetivo, Método, Resultados, Conclusão — dentro do limite de palavras
[ ] Palavras-chave: 3-6 termos, preferencialmente do MeSH/DeCS
[ ] Texto principal: estrutura IMRaD completa (Introdução, Métodos, Resultados, Discussão, Conclusão)
[ ] Contagem de palavras dentro do limite do periódico
[ ] Tabelas: numeradas em ordem de citação, título acima, notas abaixo, sem linhas verticais
[ ] Figuras: resolução mínima 300 dpi, formato TIFF ou EPS, legendas em arquivo separado
[ ] Abreviações: todas definidas na primeira ocorrência
[ ] Unidades: Sistema Internacional (SI)

**CATEGORIA 2 — MÉTODOS E DADOS**
[ ] Protocolo de estudo registrado (ClinicalTrials.gov, ReBEC, PROSPERO): número de registro incluído
[ ] CONSORT/STROBE/PRISMA/CARE/AGREE checklist preenchido (específico para o delineamento: ${dados.delineamento})
[ ] Tamanho amostral: cálculo descrito e justificado (${dados.amostra_estimada})
[ ] Análise estatística: software citado com versão, todos os testes declarados, nível α definido
[ ] Dados disponíveis: declaração de disponibilidade de dados (repositório ou "disponível mediante solicitação")

**CATEGORIA 3 — ÉTICA E CONFORMIDADE**
[ ] Número do parecer do CEP: [NÚMERO] — Data: [DATA]
[ ] Declaração de aprovação ética incluída nos Métodos
[ ] TCLE: obtido e referido no manuscrito
[ ] Anonimização dos participantes confirmada
[ ] Conflito de interesses: declaração de todos os autores (incluir formulário ICMJE se exigido)
[ ] Fonte de financiamento: declarada (ou "sem financiamento")
[ ] Aprovação de uso de imagens/dados institucionais (se aplicável)

**CATEGORIA 4 — FORMATAÇÃO E NORMAS DO PERIÓDICO**
[ ] Guia de autores do periódico lido integralmente
[ ] Formatação: fonte, espaçamento, margens conforme as normas do periódico
[ ] Citações: estilo correto (Vancouver/ABNT/APA) conforme normas do periódico
[ ] Referências: todas citadas no texto, todas na lista, limite de referências respeitado
[ ] Idioma revisado por falante nativo ou serviço de revisão de inglês (se submissão em inglês)
[ ] Arquivo anonimizado para revisão cega (blind review): nomes de autores removidos

**CATEGORIA 5 — ARQUIVOS PARA SUBMISSÃO**
[ ] Carta de apresentação (Cover Letter) redigida e personalizada para o periódico
[ ] Arquivo principal do manuscrito (Word .docx ou LaTeX)
[ ] Tabelas em arquivo separado (se exigido)
[ ] Figuras em arquivos individuais com resolução adequada
[ ] Material suplementar organizado e referenciado no texto
[ ] Declarações de contribuição dos autores, conflito de interesses e financiamento
[ ] Checklist de reportagem (CONSORT/STROBE/etc.) preenchido
[ ] Formulários específicos do periódico (se houver)

**CATEGORIA 6 — VERIFICAÇÃO FINAL**
[ ] Releitura completa do manuscrito por todos os autores
[ ] Verificação de plágio (Turnitin, iThenticate) — índice de similaridade < 15%
[ ] DOI ou URL de todas as referências verificados
[ ] Datas de acesso de sites atualizadas
[ ] Número de versão do manuscrito registrado localmente

**DICAS ESPECÍFICAS PARA ESTE PROJETO**
Com base no delineamento (${dados.delineamento}) e na análise prevista (${dados.analise_prevista}), liste 3-4 cuidados adicionais que este estudo específico precisa ter na submissão.

Formate o checklist de forma clara e pronta para impressão ou uso digital.

ESTILO NAS DICAS ESPECÍFICAS E NAS EXPLICAÇÕES: Escreva em prosa com ritmo variado. Inclua pelo menos 1 observação contraintuitiva ou aviso sobre erro comum. PROIBIDO: "É importante ressaltar", "Nesse contexto", "Destarte", "Sendo assim", "Além disso,".`
}

export function buildDocumentoPrompt(
  tipo: TipoDocumento,
  dados: DadosProjeto,
  trabalhoTitulo?: string,
  referencias?: Referencia[],
  formato: FormatoCitacao = 'abnt',
): { system: string; user: string } {
  let user: string

  switch (tipo) {
    case 'revisao_literatura':
      user = buildRevisaoLiteratura(dados, trabalhoTitulo)
      break
    case 'protocolo_cep':
      user = buildProtocoloCep(dados, trabalhoTitulo)
      break
    case 'carta_anuencia':
      user = buildCartaAnuencia(dados, trabalhoTitulo)
      break
    case 'tcle':
      user = buildTcle(dados, trabalhoTitulo)
      break
    case 'instrumento_coleta':
      user = buildInstrumentoColeta(dados)
      break
    case 'calculo_amostral':
      user = buildCalculoAmostral(dados)
      break
    case 'guia_coleta':
      user = buildGuiaColeta(dados)
      break
    case 'protocolo_extracao':
      user = buildProtocoloExtracao(dados, trabalhoTitulo)
      break
    case 'guia_analise':
      user = buildGuiaAnalise(dados)
      break
    case 'sugestoes_periodicos':
      user = buildSugestoesPeriodicos(dados)
      break
    case 'carta_submissao':
      user = buildCartaSubmissao(dados, trabalhoTitulo)
      break
    case 'checklist_submissao':
      user = buildChecklistSubmissao(dados)
      break
    default: {
      const _exhaustive: never = tipo
      void _exhaustive
      user = `Gere um documento completo para o tipo "${tipo}" com base nos dados do projeto.`
    }
  }

  // Portão de qualidade — normas rigorosas da seção (Revisão de Literatura)
  let system = SYSTEM_PROMPT
  if (tipo === 'revisao_literatura') {
    system += `\n${getNormasSecao('revisao_literatura', 'Revisão de Literatura')}`
  }

  // Injeta as referências reais + instrução de ancoragem (densidade máxima) no system prompt
  if (referencias && referencias.length > 0) {
    system += `

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${referencias.length} REFERÊNCIAS REAIS DISPONÍVEIS — A BASE DO DOCUMENTO
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cada linha mostra: a citação no texto → o título do estudo.

${formatarRefsParaPrompt(referencias, formato)}
${buildInstrucaoCitacaoReferencias(referencias, formato)}`
  } else {
    system += `\n${buildInstrucaoCitacaoReferencias([], formato)}`
  }

  return { system, user }
}
